#!/usr/bin/env bash
# ==============================================================================
# MyHospital Backend — First-Time Server Setup
# ==============================================================================
# Run this script ONCE on a fresh Ubuntu Lightsail instance to:
#   1. Install Docker & Docker Compose
#   2. Set up a GitHub deploy key (for private repo access)
#   3. Clone the repository
#   4. Generate the production .env from the template
#   5. Build and start all services
#
# Usage:
#   # Copy this script to the server, then:
#   chmod +x setup-server.sh
#   ./setup-server.sh
#
# Prerequisites:
#   - Ubuntu 22.04+ (Lightsail default)
#   - SSH access with sudo privileges
# ==============================================================================

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
REPO_URL="git@github.com:DarshanRevankar24/MyHospital-backend.git"
PROJECT_DIR="$HOME/MyHospital-backend"
COMPOSE_FILE="docker-compose.prod.yml"
DEPLOY_KEY_PATH="$HOME/.ssh/github-deploy-key"

# ── Colors ────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
step()  { echo -e "\n${CYAN}══════════════════════════════════════════════════${NC}"; echo -e "${CYAN} $*${NC}"; echo -e "${CYAN}══════════════════════════════════════════════════${NC}"; }

# ── Step 1: Install Docker ───────────────────────────────────────────────────
install_docker() {
    step "Step 1/5: Docker"

    if command -v docker &>/dev/null; then
        info "Docker is already installed: $(docker --version)"
    else
        info "Installing Docker…"
        sudo apt-get update -y
        sudo apt-get install -y ca-certificates curl gnupg

        # Add Docker's official GPG key
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
            sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg

        # Set up the repository
        echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
            https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        sudo apt-get update -y
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

        # Allow current user to run docker without sudo
        sudo usermod -aG docker "$USER"
        info "Docker installed successfully."
    fi

    # Ensure git is available
    if ! command -v git &>/dev/null; then
        info "Installing git…"
        sudo apt-get install -y git
    fi
}

# ── Step 2: Set up GitHub deploy key ─────────────────────────────────────────
setup_deploy_key() {
    step "Step 2/5: GitHub Deploy Key"

    if [ -f "$DEPLOY_KEY_PATH" ]; then
        info "Deploy key already exists at $DEPLOY_KEY_PATH"
    else
        info "Generating SSH deploy key for GitHub…"
        ssh-keygen -t ed25519 -C "lightsail-deploy-key" -f "$DEPLOY_KEY_PATH" -N ""
        info "Deploy key generated."
    fi

    # Configure SSH to use this key for github.com
    local ssh_config="$HOME/.ssh/config"
    if ! grep -q "github.com" "$ssh_config" 2>/dev/null; then
        cat >> "$ssh_config" <<EOF

# GitHub deploy key (auto-generated by setup-server.sh)
Host github.com
    HostName github.com
    User git
    IdentityFile $DEPLOY_KEY_PATH
    IdentitiesOnly yes
    StrictHostKeyChecking accept-new
EOF
        chmod 600 "$ssh_config"
        info "SSH config updated to use deploy key for github.com"
    else
        info "SSH config already has a github.com entry — skipping."
    fi

    echo
    warn "┌──────────────────────────────────────────────────────────────┐"
    warn "│  ADD THIS PUBLIC KEY TO YOUR GITHUB REPO AS A DEPLOY KEY:   │"
    warn "└──────────────────────────────────────────────────────────────┘"
    echo
    echo -e "${CYAN}"
    cat "${DEPLOY_KEY_PATH}.pub"
    echo -e "${NC}"
    echo
    warn "Go to: https://github.com/DarshanRevankar24/MyHospital-backend/settings/keys"
    warn "Click 'Add deploy key', paste the key above, and save."
    warn "(Read-only access is sufficient.)"
    echo
    read -rp "Press Enter after you've added the deploy key to GitHub… "

    # Verify connectivity
    info "Testing GitHub SSH connectivity…"
    if ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
        info "GitHub SSH authentication successful!"
    else
        # ssh -T returns exit code 1 even on success with GitHub
        if ssh -T git@github.com 2>&1 | grep -qi "hi\|successfully"; then
            info "GitHub SSH authentication successful!"
        else
            error "GitHub SSH authentication failed. Please check:"
            error "  1. The deploy key was added to the repo"
            error "  2. The key at $DEPLOY_KEY_PATH matches"
            error ""
            error "Debug with: ssh -vT git@github.com"
            exit 1
        fi
    fi
}

# ── Step 3: Clone the repository ─────────────────────────────────────────────
clone_repo() {
    step "Step 3/5: Clone Repository"

    if [ -d "$PROJECT_DIR/.git" ]; then
        info "Repository already cloned at $PROJECT_DIR"
        return
    fi

    info "Cloning repository…"
    git clone "$REPO_URL" "$PROJECT_DIR"
    info "Repository cloned to $PROJECT_DIR"
}

# ── Step 4: Set up the .env file ─────────────────────────────────────────────
setup_env() {
    step "Step 4/5: Production Environment"

    local env_file="$PROJECT_DIR/backend/.env"
    local example_file="$PROJECT_DIR/backend/.env.production.example"

    if [ -f "$env_file" ]; then
        warn ".env already exists at $env_file — skipping."
        warn "To regenerate, delete it and re-run this script."
        return
    fi

    if [ ! -f "$example_file" ]; then
        error "Template not found: $example_file"
        exit 1
    fi

    info "Generating production .env from template…"
    cp "$example_file" "$env_file"

    # Auto-generate SECRET_KEY
    local secret_key
    secret_key=$(openssl rand -hex 32)
    sed -i "s|<generate-a-64-char-hex-string>|${secret_key}|" "$env_file"

    # Auto-generate POSTGRES_PASSWORD
    local pg_password
    pg_password=$(openssl rand -hex 24)
    sed -i "s|<strong-random-password>|${pg_password}|" "$env_file"

    info "Auto-generated SECRET_KEY and POSTGRES_PASSWORD."
    echo
    warn "┌──────────────────────────────────────────────────────────────┐"
    warn "│  EDIT THE .env FILE BEFORE CONTINUING:                      │"
    warn "│                                                             │"
    warn "│  nano $env_file"
    warn "│                                                             │"
    warn "│  At minimum, set:                                           │"
    warn "│    • CORS_ORIGINS (your frontend domain)                    │"
    warn "│    • Review POSTGRES_USER / POSTGRES_DB names               │"
    warn "│    • AWS_* vars if using push notifications                 │"
    warn "│                                                             │"
    warn "│  SECRET_KEY and POSTGRES_PASSWORD are already generated.    │"
    warn "└──────────────────────────────────────────────────────────────┘"
    echo
    read -rp "Press Enter after you've edited .env (or Ctrl+C to abort)… "
}

# ── Step 5: Build and start services ─────────────────────────────────────────
start_services() {
    step "Step 5/5: Build & Start Services"

    info "Building and starting production services…"
    info "(This will take a few minutes on first run.)"

    cd "$PROJECT_DIR"

    # Use sg to run docker in the docker group context without requiring re-login.
    # This is needed because usermod -aG doesn't take effect until next login.
    if groups | grep -q docker; then
        docker compose -f "$COMPOSE_FILE" up -d --build
    else
        info "Running docker compose via 'sg docker' (group not active in current session)…"
        sg docker -c "docker compose -f $COMPOSE_FILE up -d --build"
    fi

    echo
    info "Services are starting. Checking status…"
    echo

    if groups | grep -q docker; then
        docker compose -f "$COMPOSE_FILE" ps
    else
        sg docker -c "docker compose -f $COMPOSE_FILE ps"
    fi
}

# ── Main ─────────────────────────────────────────────────────────────────────
main() {
    echo
    echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║      MyHospital Backend — Production Server Setup          ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo

    install_docker
    setup_deploy_key
    clone_repo
    setup_env
    start_services

    echo
    echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  ✅  Setup complete!                                        ║${NC}"
    echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
    echo -e "${GREEN}║                                                             ║${NC}"
    echo -e "${GREEN}║  Project  : $PROJECT_DIR${NC}"
    echo -e "${GREEN}║  Compose  : $COMPOSE_FILE${NC}"
    echo -e "${GREEN}║  Env file : $PROJECT_DIR/backend/.env${NC}"
    echo -e "${GREEN}║                                                             ║${NC}"
    echo -e "${GREEN}║  Commands:                                                  ║${NC}"
    echo -e "${GREEN}║    cd $PROJECT_DIR${NC}"
    echo -e "${GREEN}║    docker compose -f $COMPOSE_FILE ps${NC}"
    echo -e "${GREEN}║    docker compose -f $COMPOSE_FILE logs -f api${NC}"
    echo -e "${GREEN}║    docker compose -f $COMPOSE_FILE down${NC}"
    echo -e "${GREEN}║                                                             ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo
    warn "NEXT STEPS:"
    warn "  1. Verify the API is running:  curl http://localhost:8000/api/v1/health"
    warn "  2. Set up GitHub Actions secrets (see README or deployment guide)"
    warn "  3. Generate an SSH key for GitHub Actions to deploy (separate from the deploy key above)"
}

main "$@"
