"""add_medicine_type

Revision ID: 50a26f0268ad
Revises: addb8d53580e
Create Date: 2026-08-27 10:28:57.404584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a26f0268ad'
down_revision: Union[str, Sequence[str], None] = 'addb8d53580e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('medicine_type', sa.Enum('TABLET', 'SYRUP', 'INJECTION', 'CAPSULE', 'DROPS', 'OINTMENT', 'CREAM', 'GEL', 'POWDER', 'OTHER', name='medicinetype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication', 'medicine_type')
    # ### end Alembic commands ###
