"""add_medication_module

Revision ID: addb8d53580e
Revises: 002_family_relation_doc_access
Create Date: 2026-08-26 17:20:15.890318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addb8d53580e'
down_revision: Union[str, Sequence[str], None] = '002_family_relation_doc_access'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'device_token', ['id'])
    op.create_unique_constraint(None, 'family_connection', ['id'])
    op.create_unique_constraint(None, 'medication', ['id'])
    op.create_unique_constraint(None, 'notification_log', ['id'])
    op.create_unique_constraint(None, 'notification_preference', ['id'])
    op.alter_column('user', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'blood_group',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
    op.alter_column('user', 'kyc_document_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user', 'kyc_document_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'address_line1',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('user', 'state',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('user', 'pincode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('user', 'pincode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user', 'state',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('user', 'address_line1',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'kyc_document_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'kyc_document_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user', 'blood_group',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('user', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(None, 'notification_preference', type_='unique')
    op.drop_constraint(None, 'notification_log', type_='unique')
    op.drop_constraint(None, 'medication', type_='unique')
    op.drop_constraint(None, 'family_connection', type_='unique')
    op.drop_constraint(None, 'device_token', type_='unique')
    # ### end Alembic commands ###
